### ISSUE TITLE
XML Parsing Error "not well-formed Location"

### ISSUE THREAD

**Issue by Seb35** [guillaumevincent/vue-polyglot#8]
When using LessPass as Firefox extension, I got the warning "Erreur d’analyse XML : mal formé
Emplacement : jar:file://[firefox-profile]/extensions/contact@lesspass.com.xpi!/dist/i18n/fr.json
Numéro de ligne 1, Colonne 1 :" in the browser console log. I guess it is more precisely an issue in this library, hence filling an issue here.

**Comment by Seb35** [comment]
Searching a bit about this type of warning, there is for instance [this link on StackOverflow](https://stackoverflow.com/questions/677902/not-well-formed-error-in-firefox-when-loading-json-file-with-xmlhttprequest). It seems the MIME type should be explictely defined as "application/json". I’m not fluent in Vue.js, hopefully someone else will know how to implement this properly in Vue.js given this report.

**Comment by guillaumevincent** [comment]
I can only check this on monday :(

**Comment by guillaumevincent** [comment]
I don't get this issue on Firefox
I close. 
Feel free to post on this thread to ask for extra help.
